tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://github.com/dice-project/DICE-Deployment-Cloudify/releases/download/0.7.9/full.yaml


node_templates:

  nginx:
    type: dice.components.docker.Container
    properties:
      host: tcp://10.50.51.27:2375
      image: nginx
      tag: latest
      port_mapping:
        80/tcp: null


outputs:
  id: { value: { get_attribute: [ nginx, id ] } }
  name: { value: { get_attribute: [ nginx, name ] } }
  ports_user: { value: { get_property: [ nginx, port_mapping ] } }
  ports_inst: { value: { get_attribute: [ nginx, port_mapping ] } }
